version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/nodejs
hooks:
  AfterInstall:
    - location: mongo_install.sh
      runas: root
  ApplicationStart:
    - location : after_install_script.sh
      runas: root	
