version: 0.0
os: ubuntu
files:
  - source: /
    destination: /tmp/nodejs
hooks:
  AfterInstall:
    - location: mongo_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location : after_install_script.sh
      runas: root	
