version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/port81
hooks:
  ApplicationStop:
    - location: deregister_from_elb.sh
      runas: root
  ApplicationStart:
    - location: register_with_elb.sh
    - location: after_install_script.sh
      runas: root
